---
pool:
  name: 'Azure Pipelines'
  vmImage: ubuntu-latest

trigger:
  - master

resources:
  repositories:
    - repository: 'azuredevopstemplates'
      name: 'AzureDevOpsReusableTemplates'
      type: 'github'
      ref: 'refs/heads/main'

steps:
  - template: java/maven-build-simple.yaml@azuredevopstemplates
    parameters:
      jdkVersion: '1.8'